#!/bin/bash

echo "🔍 AUTH FLOW DIAGNOSTIC"
echo ""
echo "================================================================"
echo ""

# Step 1: Test /auth/me without cookies (should fail)
echo "📍 Step 1: Test /auth/me endpoint (no cookies)"
echo "Expected: 401 Unauthorized"
echo ""
curl -s -w "\nHTTP Status: %{http_code}\n\n" http://localhost:4000/auth/me

echo "================================================================"
echo ""
echo "📍 Step 2: Get your session cookie"
echo ""
echo "ACTION REQUIRED:"
echo "1. Open browser DevTools (F12)"
echo "2. Go to: Application tab → Cookies → http://localhost:3001"
echo "3. Find the 'session' cookie"
echo "4. Copy its VALUE"
echo "5. Run this command:"
echo ""
echo "   curl -H 'Cookie: session=<YOUR_SESSION_VALUE>' http://localhost:4000/auth/me"
echo ""
echo "This will test if your session cookie works with the auth-server."
echo ""
echo "================================================================"
echo ""
echo "📍 Step 3: Check Next.js terminal logs"
echo ""
echo "Your Next.js dev server should show these logs when you visit /rraasi-music:"
echo "  [My Tracks API] ===== AUTH DEBUG ====="
echo "  [My Tracks API] Has cookie header: true/false"
echo "  [My Tracks API] getCurrentUser result: USER FOUND / NULL"
echo ""
echo "If you DON'T see these logs, the page might be cached."
echo "Try: Hard refresh (Cmd+Shift+R or Ctrl+F5)"
echo ""
