'use server';

import { getAdminDb, initAdmin } from '@/lib/firebase-admin';
import { google } from 'googleapis';
import { IntegrationToken, INTEGRATION_TOKENS_COLLECTION } from '@/lib/types/integrations';
import { generateVideoFromAudio } from '@/lib/media/video-generator';
import fs from 'fs';

export async function distributeMusic(params: { trackId: string, shareId: string, platform: 'youtube' | 'soundcloud', userId: string }) {
    try {
        const { trackId, shareId, platform, userId } = params;

        if (!trackId || !platform || !userId) {
            return { success: false, error: 'Missing required fields' };
        }

        initAdmin();
        const db = getAdminDb();

        const docId = shareId || trackId;
        const trackDoc = await db.collection('music_tracks').doc(docId).get();
        
        if (!trackDoc.exists) {
            return { success: false, error: 'Track doc not found' };
        }
        
        let trackData = trackDoc.data()!;
        
        if (trackData.tracks && Array.isArray(trackData.tracks)) {
            const nestedClip = trackData.tracks.find((t: any) => t.sunoId === trackId || `${trackData.taskId || docId}` === trackId);
            if (nestedClip) {
                trackData = {
                    ...trackData,
                    ...nestedClip,
                    id: docId,
                    sunoId: trackId
                };
            }
        } else {
             trackData.id = docId;
             trackData.sunoId = trackId;
        }

        const tokenDoc = await db.collection(INTEGRATION_TOKENS_COLLECTION).doc(`${userId}_${platform}`).get();
        if (!tokenDoc.exists) {
            return { success: false, error: `Not connected to ${platform}` };
        }
        const tokenData = tokenDoc.data() as IntegrationToken;

        if (platform === 'youtube') {
            return await uploadToYouTube(userId, trackData, tokenData, db);
        } else if (platform === 'soundcloud') {
            return { success: false, error: 'SoundCloud upload implementation requires verifiction of API access level.' };
        } else {
            return { success: false, error: 'Unsupported platform' };
        }
    } catch (e: any) {
        console.error('Server Action distributeMusic Error:', e);
        return { success: false, error: e.message || 'Internal Server Error' };
    }
}

async function uploadToYouTube(userId: string, trackData: any, token: IntegrationToken, db: FirebaseFirestore.Firestore) {
    let videoPath = '';

    try {
        const oauth2Client = new google.auth.OAuth2(
            process.env.YOUTUBE_CLIENT_ID,
            process.env.YOUTUBE_CLIENT_SECRET
        );
        oauth2Client.setCredentials({
            access_token: token.accessToken,
            refresh_token: token.refreshToken,
            expiry_date: token.expiryDate
        });

        // 1. Get Video Source
        let audioUrl = trackData.audio_url || trackData.audioUrl;
        let imageUrl = trackData.image_url || trackData.imageUrl || trackData.sourceImageUrl;
        let videoUrl = trackData.video_url || trackData.videoUrl;

        if (videoUrl) {
            console.log(`[YouTube] Using pre-generated video: ${videoUrl}`);
            const response = await fetch(videoUrl);
            if (!response.ok) throw new Error(`Failed to download video from ${videoUrl}`);
            
            const arrayBuffer = await response.arrayBuffer();
            const buffer = Buffer.from(arrayBuffer);
            videoPath = `/tmp/video_yt_${trackData.id || Date.now()}.mp4`;
            fs.writeFileSync(videoPath, buffer);
        } else {
            console.log(`[YouTube] Generating video from audio: ${audioUrl}`);
            if (!audioUrl || !imageUrl) {
                throw new Error('Missing audio or image URL in track data for video generation');
            }

            videoPath = await generateVideoFromAudio({
                audioUrl,
                imageUrl,
                outputName: `youtube_${trackData.id || Date.now()}`
            });
        }

        // 2. Upload to YouTube
        const youtube = google.youtube({ version: 'v3', auth: oauth2Client });
        
        const title = trackData.title || 'Unknown Track';
        
        let fullDescription = trackData.description || trackData.prompt || `A beautiful track generated by Rraasi Music for ${userId}.`;

        if (trackData.story) {
            fullDescription += `\n\n📖 The Story Behind the Track:\n${trackData.story}`;
        }
        
        if (trackData.lyrics) {
            fullDescription += `\n\n🎵 Lyrics:\n${trackData.lyrics}`;
        }

        if (trackData.healingBenefits && trackData.healingBenefits.length > 0) {
            fullDescription += `\n\n💖 Healing Benefits:\n- ${trackData.healingBenefits.join('\n- ')}`;
        }
        
        fullDescription += `\n\nDiscover more spiritual wisdom and healing music on the Rraasi app!`;

        let youtubeTags = ['AI Music', 'Satsang', 'Meditation', 'Rraasi'];
        if (trackData.tags) {
            if (Array.isArray(trackData.tags)) {
                youtubeTags = [...new Set([...youtubeTags, ...trackData.tags])];
            } else if (typeof trackData.tags === 'string') {
                const cleanTags = trackData.tags.split(',').map((t: string) => t.trim()).filter(Boolean);
                youtubeTags = [...new Set([...youtubeTags, ...cleanTags])];
            }
        }

        // YouTube API rejects < and > characters in title and description
        const cleanTitle = title.replace(/[<>]/g, '').substring(0, 100);
        const cleanDescription = fullDescription.replace(/[<>]/g, '').substring(0, 5000);

        const res = await youtube.videos.insert({
            part: ['snippet', 'status'],
            requestBody: {
                snippet: {
                    title: cleanTitle,
                    description: cleanDescription,
                    categoryId: '10', // Music
                    tags: youtubeTags.slice(0, 15)
                },
                status: {
                    privacyStatus: 'private' // Default to private for safety
                }
            },
            media: {
                body: fs.createReadStream(videoPath)
            }
        });

        // 3. Update track status
        await db.collection('music_tracks').doc(trackData.id).set({
            youtubeId: res.data.id,
            youtubeUrl: `https://youtu.be/${res.data.id}`,
            youtubeUploadStatus: 'completed',
            updatedAt: Date.now()
        }, { merge: true });

        if (fs.existsSync(videoPath)) fs.unlinkSync(videoPath);

        return {
            success: true,
            platform: 'youtube',
            videoId: res.data.id,
            url: `https://youtu.be/${res.data.id}`
        };

    } catch (err: any) {
        if (fs.existsSync(videoPath)) fs.unlinkSync(videoPath);
        console.error('YouTube upload failed:', err);
        
        const errorMessage = err.message || '';
        if (errorMessage.includes('exceeded the number of videos') || errorMessage.includes('quotaExceeded')) {
            return { success: false, error: 'QUOTA_EXCEEDED: YouTube Daily Upload Limit Reached. Quota resets at Midnight Pacific Time (PT).' };
        }
        
        return { success: false, error: `YouTube upload failed: ${errorMessage}` };
    }
}

export async function disconnectPlatform(params: { userId: string, platform: 'youtube' | 'soundcloud' }) {
    const { userId, platform } = params;
    
    if (!userId || !platform) {
        throw new Error('Missing required fields');
    }

    initAdmin();
    const db = getAdminDb();

    // Delete the integration token
    await db.collection(INTEGRATION_TOKENS_COLLECTION).doc(`${userId}_${platform}`).delete();

    return { success: true };
}
