'use server';

import { getAdminDb, initAdmin } from '@/lib/firebase-admin';
import { google } from 'googleapis';
import { IntegrationToken, INTEGRATION_TOKENS_COLLECTION } from '@/lib/types/integrations';
import { generateVideoFromAudio } from '@/lib/media/video-generator';
import fs from 'fs';

export async function distributeMusic(params: { trackId: string, shareId: string, platform: 'youtube' | 'soundcloud', userId: string }) {
    const { trackId, shareId, platform, userId } = params;

    if (!trackId || !platform || !userId) {
        throw new Error('Missing required fields');
    }

    initAdmin();
    const db = getAdminDb();

    // 1. Fetch Track Data using shareId as the document ID (or fallback to trackId if missing)
    const docId = shareId || trackId;
    const trackDoc = await db.collection('music_tracks').doc(docId).get();
    
    if (!trackDoc.exists) {
        throw new Error('Track doc not found');
    }
    
    let trackData = trackDoc.data()!;
    
    // If track is inside array, extract the specific clip info
    if (trackData.tracks && Array.isArray(trackData.tracks)) {
        const nestedClip = trackData.tracks.find((t: any) => t.sunoId === trackId || `${trackData.taskId || docId}` === trackId);
        if (nestedClip) {
            trackData = {
                ...trackData,
                ...nestedClip,
                id: docId,
                sunoId: trackId
            };
        }
    } else {
         trackData.id = docId;
         trackData.sunoId = trackId;
    }

    // 2. Fetch Integration Token
    const tokenDoc = await db.collection(INTEGRATION_TOKENS_COLLECTION).doc(`${userId}_${platform}`).get();
    if (!tokenDoc.exists) {
        throw new Error(`Not connected to ${platform}`);
    }
    const tokenData = tokenDoc.data() as IntegrationToken;

    // 3. Process logic based on platform
    if (platform === 'youtube') {
        return await uploadToYouTube(userId, trackData, tokenData, db);
    } else if (platform === 'soundcloud') {
        throw new Error('SoundCloud upload implementation requires verifiction of API access level.');
    } else {
        throw new Error('Unsupported platform');
    }
}

async function uploadToYouTube(userId: string, trackData: any, token: IntegrationToken, db: FirebaseFirestore.Firestore) {
    let videoPath = '';

    try {
        const oauth2Client = new google.auth.OAuth2(
            process.env.YOUTUBE_CLIENT_ID,
            process.env.YOUTUBE_CLIENT_SECRET
        );
        oauth2Client.setCredentials({
            access_token: token.accessToken,
            refresh_token: token.refreshToken,
            expiry_date: token.expiryDate
        });

        // 1. Get Video Source
        let audioUrl = trackData.audio_url || trackData.audioUrl;
        let imageUrl = trackData.image_url || trackData.imageUrl || trackData.sourceImageUrl;
        let videoUrl = trackData.video_url || trackData.videoUrl;

        if (videoUrl) {
            console.log(`[YouTube] Using pre-generated video: ${videoUrl}`);
            const response = await fetch(videoUrl);
            if (!response.ok) throw new Error(`Failed to download video from ${videoUrl}`);
            
            const arrayBuffer = await response.arrayBuffer();
            const buffer = Buffer.from(arrayBuffer);
            videoPath = `/tmp/video_yt_${trackData.id || Date.now()}.mp4`;
            fs.writeFileSync(videoPath, buffer);
        } else {
            console.log(`[YouTube] Generating video from audio: ${audioUrl}`);
            if (!audioUrl || !imageUrl) {
                throw new Error('Missing audio or image URL in track data for video generation');
            }

            videoPath = await generateVideoFromAudio({
                audioUrl,
                imageUrl,
                outputName: `youtube_${trackData.id || Date.now()}`
            });
        }

        // 2. Upload to YouTube
        const youtube = google.youtube({ version: 'v3', auth: oauth2Client });
        const title = trackData.title || 'Unknown Track';
        const description = trackData.prompt || trackData.description || `Generated by AI for ${userId}\n\nListen to more on our app!`;

        const res = await youtube.videos.insert({
            part: ['snippet', 'status'],
            requestBody: {
                snippet: {
                    title: title.substring(0, 100),
                    description: description.substring(0, 5000),
                    categoryId: '10', // Music
                    tags: ['AI Music', 'Satsang', 'Meditation']
                },
                status: {
                    privacyStatus: 'private' // Default to private for safety
                }
            },
            media: {
                body: fs.createReadStream(videoPath)
            }
        });

        // 3. Update track status
        await db.collection('music_tracks').doc(trackData.id).set({
            youtubeId: res.data.id,
            youtubeUrl: `https://youtu.be/${res.data.id}`,
            youtubeUploadStatus: 'completed',
            updatedAt: Date.now()
        }, { merge: true });

        if (fs.existsSync(videoPath)) fs.unlinkSync(videoPath);

        return {
            success: true,
            platform: 'youtube',
            videoId: res.data.id,
            url: `https://youtu.be/${res.data.id}`
        };

    } catch (err: any) {
        if (fs.existsSync(videoPath)) fs.unlinkSync(videoPath);
        console.error('YouTube upload failed:', err);
        throw new Error(`YouTube upload failed: ${err.message}`);
    }
}

export async function disconnectPlatform(params: { userId: string, platform: 'youtube' | 'soundcloud' }) {
    const { userId, platform } = params;
    
    if (!userId || !platform) {
        throw new Error('Missing required fields');
    }

    initAdmin();
    const db = getAdminDb();

    // Delete the integration token
    await db.collection(INTEGRATION_TOKENS_COLLECTION).doc(`${userId}_${platform}`).delete();

    return { success: true };
}
